### ISSUE TITLE
As record manager i want to be able to abort the destruction process,  

### ISSUE THREAD

**Issue by JurjenBert** [GemeenteUtrecht/record-management-app#28]
so that the proces doesnt have to be completed if for example the comments from de proces owner are so extensive, that a new list is appropriate. The cases that were on the VL can now free to be selected for another VL. 

Similarly the archivaris can provide feedback to the record manager which makes cancelling the process the most logic step for the record manager. For example: the archivaris notes that none of the cases on the VL should not be destroyed but should instead be bewaard (whats that in english?) 

BTW: this is not the happy flow and should not occur much.  If this occurs the record manager isn't doing his or her work very well.

**Comment by annashamray** [comment]
In this issue we'll implement the missing part of the process - the record manager processing suggestions from the reviewer on the destruction list.

As a record manager I receive a notification that my DL has been reviewed. I click on the related DL from my landing page and see the detail page (which is to be implemented). The detail page has the list of DL items similar to the reviewer detail page. 
If the item is suggested to be changed or removed it should be highlighted.

When I click on the item I'll see the modal with the details or the item review. The available options are:

* the case where it is suggested for removal (rather than changing) is much more simple - I think that just boils down to showing it was suggested for removal and the RM has to accept that
*  the case where changes are requested should bring up a modal or something when you click that DL item, showing the remarks on the left panel (or top, whatever works best), and there should be at least two fields in a form to edit the archive parameters:
    * `archiefnominatie`: `Zaak.archiefnominatie` which is either `blijvend_bewaren` or `vernietigen`, with the current value pre-selected (that is `vernietigen`, or it wouldn't be on this list in the first place)
    * `archiefactiedatum`: the date can be changed, and it should probably be a date in the future of the current date

editing the object will also remove it from the list of items to be effectively destroyed


The wireframe for the modal: 
![IMG_20200703_112228](https://user-images.githubusercontent.com/47745906/86457827-8ff6a600-bd24-11ea-95aa-0d522af2e873.jpg)
